### PR TITLE
Add a test case involving -fno-warn-missing-signatures

### PR DESCRIPTION
**Pull request by zliu41**
I was trying to run ghcide on https://github.com/agda/agda, and the majority of the modules failed. What I observed was
- `Agda.cabal` declares missing signatures as fatal (`-Werror=missing-signatures`)
- `Lexer.hs` (a generated file) has missing signatures, but it disables the warning by `{-# OPTIONS_GHC -fno-warn-missing-signatures #-}`.
- However, ghcide still failed to typecheck `Lexer.hs`, citing missing signatures. `Lexer.hs` is transitively imported by a lot of modules.

This PR fixes it by only enabling non-fatal warnings in `DynFlags`.

### CODE REVIEW

**Comment by wz1000** [comment]
Seems reasonable to me, but I think a better way to achieve the same goal would be to strip out `-Werror` entirely. Maybe we can still "upgrade" the `-Werror` diagnostics to errors when presenting them to the user, like we do for type errors.

**Comment by wz1000** [comment]
Closing since this should be fixed by #738. Thanks for bringing attention to this!

**Comment by pepeiborra** [comment]
I agree that #738 is a better solution but the test in this PR is still relevant. 
@zliu41 would you be able to edit the PR down to the tests, and rebase?

**Review by pepeiborra — CHANGES_REQUESTED** [review]
Edit the PR down to the tests

**Comment by zliu41** [comment]
Ok cool, I confirmed that the problem is resolved in HEAD.
Reverted the change and only keeping the test.
Thanks @wz1000 @pepeiborra !

**Review by pepeiborra — APPROVED** [review]

**Pull request merged**
