### PR TITLE
Avoid calling kick explicitly

### PR DESCRIPTION
**Pull request by pepeiborra**
This change leverages that rules are rerun by shakeRunDatabase.
It allows users of ghcide as a library to use their own kick

### CODE REVIEW

**Comment by wz1000** [comment]
I was skeptical of this in the `hlint` plugin as well. Do we really want to run `kick` so often? Why should we run kick when we actually want to compute an unrelated rule? If we are computing a rule, its dependencies will be checked for freshness anyway.

Can we at least deprioritize `kick`?

The documentation for `action` explicitly mentions "only cheap operations should be performed"

**Comment by pepeiborra** [comment]
This is a pure refactoring, isn't it? My recollection is that we always call `kick` on a `shakeRestart`.

**Comment by wz1000** [comment]
Yes, but I'm concerned about `runAction`/`shakeEnqueue`.

**Comment by pepeiborra** [comment]
What is your concern? There is no change in `runAction` / `shakeEnqueue` as far as I can see, since neither of them calls `shakeRunDatabase`. 

This change is motivated by a custom LSP server we have at work, half-built on top of ghcide 0.0.5, which uses this approach to install a custom `kick`.

**Review by wz1000 — APPROVED** [review]

**Pull request merged**
