### PR TITLE
Changes from prepare for release 0.4.0

### PR DESCRIPTION
**Pull request by jneira**
* cherry-picking 153536b
* needed for bump up upper bound for ghcide in hls and hls-plugin-api

### CODE REVIEW

**Comment by jneira** [comment]
@wz1000 those cherry-picks would make a hypotetical new pull request to master harder?

**Comment by wz1000** [comment]
What do you mean?

**Comment by jneira** [comment]
If you had to do a new pull request to merge actual hls-3.3 (with my lastest cherry-picks) onto master (like #784), these cherry-picks would make it harder for you in any way?
If it is so i would wait until #784 is merged.

**Comment by jneira** [comment]
I guess my lack of git foo makes me too cautios :stuck_out_tongue:

**Pull request merged**
