### PR TITLE
Run desugarer (not working)

### PR DESCRIPTION
**Pull request by georgefst**
A very rudimentary first attempt at solving #107, which is the main thing I still miss from HIE.

This is my first foray in to the internals of Ghcide, and, frankly, I don't know what I'm doing... Although it was marked "good first issue", so I guess I can't be too far off.

Hopefully someone can tell me why this doesn't yet work - I'd expect to see an "incomplete pattern match" warning on:

```hs
f = \case
    True -> ()
```

### CODE REVIEW

**Comment by wz1000** [comment]
Notice that we already have `generateCoreRule` which does exactly this.

However, I plan to address this in #836

**Comment by wz1000** [comment]
BTW, the reason this doesn't work is because you don't actually call the rule from anywhere :)

**Comment by georgefst** [comment]
> BTW, the reason this doesn't work is because you don't actually call the rule from anywhere :)

Ha, I did wonder about that. Although that would seem to mean that `typeCheckRule`, which this was based on, isn't called from anywhere either. 😕

> Notice that we already have `generateCoreRule` which does exactly this.

At a glance, the implementation looks quite different - does `generateCoreRule` go further?

> However, I plan to address this in #836

Wow that's weird timing - I'd been meaning to look in to this all year...

**Comment by wz1000** [comment]
> Ha, I did wonder about that. Although that would seem to mean that `typeCheckRule`, which this was based on, isn't called from anywhere either. confused

`typecheckRule` and `generateCoreRule` merely define the shake rule. They are called when we invoke `use Typecheck` or `use GenerateCore`. So to fix your code, you would need to `use_ Desugar` somewhere.

`generateCoreRule` is essentially calling `compileModule`, which calls `desugarModule` as you did, but also optionally runs the simplifier, and also tidies the Core produced using `tidyProgram` (which makes the Core suitable for further use for compilation/bytecode generation).

**Comment by georgefst** [comment]
> you would need to `use_ Desugar` somewhere

Aha, of course - thanks

**Pull request closed without merging**
