### PR TITLE
[WIP] Set hscTarget == HscInterpreted when desugaring

### LINKED ISSUE #537: ModBreaks.modBreaks_array not initialised
Tried to use ghcide on a cabal v2 project I hadn't tried it on before, in a bunch of files I now get:

```
  ModBreaks.modBreaks_array not initialised
  CallStack (from HasCallStack):
  error, called at compiler/ghci/ByteCodeTypes.hs:173:24 in ghc:ByteCodeTypes
```

when I run `ghcide src`.

My `hie.yaml` looks like:

```yaml
cradle:
  cabal:
    component: "lib:thingy"
```

so nothing too fancy there.

### PR DESCRIPTION
**Pull request by bgamari**
GHC 8.10.1 and earlier will fail to produce valid breakpoint information
during desugaring unless hscTarget==HscInterpreted. Specifically the
information that it *does* produce contains a bottom (namely
BreakArray). We can end up stumbling over this bottom later in the
pipeline. Avoid this by setting hscTarget appropriately during
desugaring.

Frankly, this whole situation isn't very satisfactory. The meaning of
hscTarget is incredibly squishy; it's only via a knowledge of the
internals of the compiler that I believe this to be safe. This is an
area of GHC which probably deserves some refactoring. A single global
"target" makes very little sense in a context like ghcide's.

Fixes #537.

# To-do

 * [ ] Local testing

### CODE REVIEW

**Comment by bgamari** [comment]
@cocreature, unfortunately I've found that this doesn't workaround the issue. I've been meaning to build a profiled compiler to work out why this is the case. However, it will likely be a few weeks before I have time to do this.

**Comment by cocreature** [comment]
> However, it will likely be a few weeks before I have time to do this.

No worries, thanks a lot for looking into it!

**Comment by ndmitchell** [comment]
@bgamari are you likely to get back to this? If not, any tips to add to the original ticket, ideally so someone else can pick it up?

**Comment by wz1000** [comment]
Can we work around this by simply setting `mg_modBreaks` to `Nothing` after desugaring?

**Comment by wz1000** [comment]
Regardless, this should not be an issue anymore because we don't run the bytecode generator since #836. So I'm closing this for now, until we decide we need to re-introduce bytecode generation.

**Pull request closed without merging**
