### PR TITLE
Preserve import paths for implicit cradles

### LINKED ISSUE #765: Loading multiple standalone files without any hie.yaml file started giving import errors.
I am currently working with the test added in https://github.com/maralorn/ghcide/commit/bd3290889152b7a63b53e32077b5b348c93ae2d1

This test started failing with `"Could not find module "B". It is not a module in the current program, or in any known package."`

Sometime in the last week.

### PR DESCRIPTION
**Pull request by pepeiborra**
Attempt to fix #765

### CODE REVIEW

**Comment by pepeiborra** [comment]
@maralorn does this fix things for you?

**Comment by maralorn** [comment]
Yes, this change fixes a test case I was using which used the implicit cradle without any config files and multiple modules.

**Review by wz1000 — APPROVED** [review]

**Review by fendor — APPROVED** [review]

**Comment by pepeiborra** [comment]
> Yes, this change fixes a test case I was using which used the implicit cradle without any config files and multiple modules.

May I ask you to test again? I just pushed a patch to fix a copy-paste error

**Pull request merged**
