### PR TITLE
GHC 8.8.4 & 8.10.2

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by pepeiborra** [comment]
Thanks! Did you investigate if any extra deps can be removed?

**Review by pepeiborra — APPROVED** [review]

**Comment by pepeiborra** [comment]
CI rerun seems broken - could you rebase or push an empty commit to force a rerun please?

**Comment by domenkozar** [comment]
Might be related to https://www.stackage.org/blog/2020/08/ghc-8-10-2-windows-workaround

**Comment by domenkozar** [comment]
Yup: `zlib             > ghc.exe: could not execute: C:/GitLabRunner/builds/2WeHDSFP/0/ghc/ghc/inplace/mingw/bin/ld.exe`

**Comment by pepeiborra** [comment]
ping @jneira help!

**Comment by jneira** [comment]
ugh, that workaround would be doable with some `sed` magic over the ghc config file but i think the ghc team ia gonna release a new version 8.10.3 with the fix so maybe the easy way is to exclude 8.10 from ci temporary:

https://github.com/haskell/ghcide/blob/84af588fa00717ad5f624dd600bfd0b0c6060090/.azure/windows-stack.yml#L8-L9

... or keep a stack8101.yaml and use it for windows until 8.10.3 is released (more user firendly)

**Comment by pepeiborra** [comment]
I'm happy with a temporary exclusion @jneira, why don't you send a separate PR to do that? 
Or alternatively @domenkozar you can make the change in this PR.

**Comment by jneira** [comment]
Yeah, will do but i would prefer to keep a stack yaml for ghc-8.10.1

**Comment by domenkozar** [comment]
Hopefully this will pass now :)

**Comment by pepeiborra** [comment]
Merged, thanks!

**Pull request merged**
