### PR TITLE
Allow to easily customise the example used for benchmarks

### PR DESCRIPTION
**Pull request by pepeiborra**

### CODE REVIEW

**Review by wz1000 — APPROVED** [review]

**Comment by wz1000** [comment]
Cabal file needs to be updated.

**Comment by wz1000** [comment]
It would be nice if we could configure the Positions (hygienicP, identifierP) too.

**Comment by pepeiborra** [comment]
> It would be nice if we could configure the Positions (hygienicP, identifierP) too.

Good point, will do. Ideally those positions would be automatically created by the benchmark suite

**Pull request merged**
