### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by pepeiborra**
Adds a Github action for benchmarking, using Cabal instead of stack (since the stack implementation gets stuck, see #893)

Builds on top of #893

### CODE REVIEW

**Review by bubba — APPROVED** [review]
I can't see any run for this PR but the workflow file makes sense to me

**Review by ndmitchell — APPROVED** [review]

**Comment by pepeiborra** [comment]
Runs: https://github.com/pepeiborra/ghcide/actions

**Review by jneira — APPROVED** [review]
LGTM
It would be great to run it in windows but it is matter of a another pr 😄

**Comment by pepeiborra** [comment]
Benchmarks do not build in Windows because of the Cairo requirement

**Pull request merged**
